# Generated by Django 4.2 on 2023-09-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_storestaff_inventorystaff_cashierstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_new_user',
            field=models.BooleanField(default=True, verbose_name='New user status'),
        ),
    ]
