# Generated by Django 4.2 on 2023-09-21 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_storestaff_inventorystaff_cashierstaff'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cashierStaff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='users.cashierstaff'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='market.customer'),
        ),
        migrations.AddField(
            model_name='productshelf',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_shelves', to='market.branch'),
        ),
        migrations.AddField(
            model_name='productshelf',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches_shelves', to='market.product'),
        ),
        migrations.AddField(
            model_name='cashier',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashiers', to='market.branch'),
        ),
        migrations.AddField(
            model_name='card',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='market.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='storeproduct',
            unique_together={('product', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='productshelf',
            unique_together={('product', 'branch')},
        ),
    ]
