# Generated by Django 4.2 on 2023-10-04 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer_nit',
        ),
        migrations.AddField(
            model_name='sale',
            name='nit',
            field=models.CharField(default='000000000', max_length=9, validators=[django.core.validators.RegexValidator(message='Nit must be 9 digits', regex='[1-9][0-9]{8}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='cashier',
            unique_together={('number', 'branch')},
        ),
    ]
